databases:
  - name: banking-system-db
    plan: free
    databaseName: banking_system_production
    user: banking_system

services:
  - type: web
    name: banking-system-backend
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: banking-system-db
          property: connectionString
      - key: BANKING_SYSTEM_DATABASE_PASSWORD
        fromDatabase:
          name: banking-system-db
          property: password
    autoDeploy: true
