services:
  - type: web
    name: sacco-app
    env: ruby
    plan: free  # change to 'starter' or 'standard' if needed
    buildCommand: "./build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        value: 08ce67527d15e415123c7fde10f87cb0
      - key: DATABASE_URL
        fromDatabase:
          name: sacco-db
          property: connectionString

databases:
  - name: sacco-db
    plan: free
    databaseName: sacco_production
    user: sacco_user
