default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres  # Change if you use a different username
  password: postgres  # Change if you set a different password
  host: localhost

development:
  <<: *default
  database: banking_system_development

test:
  <<: *default
  database: banking_system_test

production:
  <<: *default
  database: banking_system_production
  username: banking_system
  password: <%= ENV["BANKING_SYSTEM_DATABASE_PASSWORD"] %> # Use an environment variable for security
  url: <%= ENV['DATABASE_URL'] %> # Full connection URL (e.g., for deployment)


